package dev.mikko.jacksoncheck;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.zip.ZipEntry;
import java.util.zip.ZipOutputStream;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

class ScannerTest {

    /** 造一个归档。entries 是 路径 → 内容。 */
    private static byte[] zip(Map<String, String> entries) throws IOException {
        ByteArrayOutputStream bos = new ByteArrayOutputStream();
        try (ZipOutputStream zos = new ZipOutputStream(bos)) {
            for (Map.Entry<String, String> e : entries.entrySet()) {
                zos.putNextEntry(new ZipEntry(e.getKey()));
                zos.write(e.getValue().getBytes(StandardCharsets.UTF_8));
                zos.closeEntry();
            }
        }
        return bos.toByteArray();
    }

    private static Map<String, String> pomProps(String group, String version) {
        Map<String, String> m = new LinkedHashMap<>();
        m.put("META-INF/maven/" + group + "/jackson-databind/pom.properties",
                "artifactId=jackson-databind\ngroupId=" + group + "\nversion=" + version + "\n");
        return m;
    }

    private static Scanner scan(Path dir, String name, byte[] bytes) throws IOException {
        Path f = dir.resolve(name);
        Files.createDirectories(f.getParent());
        Files.write(f, bytes);
        Scanner s = new Scanner();
        s.scan(f);
        return s;
    }

    @Test
    @DisplayName("从 pom.properties 认出 2.x 坐标")
    void reads2xCoordinate(@TempDir Path dir) throws IOException {
        Scanner s = scan(dir, "lib/jackson-databind-2.18.5.jar",
                zip(pomProps(CveTable.GROUP_2X, "2.18.5")));
        assertEquals(1, s.artifacts().size());
        assertEquals(CveTable.GROUP_2X, s.artifacts().get(0).groupId());
        assertEquals("2.18.5", s.artifacts().get(0).version().toString());
        assertFalse(s.artifacts().get(0).guessedGroup());
    }

    @Test
    @DisplayName("🔴 从 pom.properties 认出 3.x 的新坐标 —— 两个 jar 文件名一模一样,只有这里分得清")
    void reads3xCoordinate(@TempDir Path dir) throws IOException {
        Scanner s = scan(dir, "lib/jackson-databind-3.1.2.jar",
                zip(pomProps(CveTable.GROUP_3X, "3.1.2")));
        assertEquals(CveTable.GROUP_3X, s.artifacts().get(0).groupId());
    }

    @Test
    @DisplayName("pom.properties 的键顺序不同也要认(不能按行序解析)")
    void keyOrderDoesNotMatter(@TempDir Path dir) throws IOException {
        Map<String, String> m = new LinkedHashMap<>();
        m.put("META-INF/maven/" + CveTable.GROUP_2X + "/jackson-databind/pom.properties",
                "#Generated by Maven\nversion=2.21.2\ngroupId=" + CveTable.GROUP_2X
                        + "\nartifactId=jackson-databind\n");
        Scanner s = scan(dir, "a.jar", zip(m));
        assertEquals("2.21.2", s.artifacts().get(0).version().toString());
    }

    @Test
    @DisplayName("Spring Boot fat jar:认出 BOOT-INF/lib 里的嵌套 jar")
    void fatJar(@TempDir Path dir) throws IOException {
        byte[] inner = zip(pomProps(CveTable.GROUP_2X, "2.18.5"));
        ByteArrayOutputStream bos = new ByteArrayOutputStream();
        try (ZipOutputStream zos = new ZipOutputStream(bos)) {
            zos.putNextEntry(new ZipEntry("BOOT-INF/lib/jackson-databind-2.18.5.jar"));
            zos.write(inner);
            zos.closeEntry();
        }
        Scanner s = scan(dir, "app.jar", bos.toByteArray());
        assertEquals(1, s.artifacts().size());
        assertEquals("2.18.5", s.artifacts().get(0).version().toString());
        assertTrue(s.artifacts().get(0).path().contains("!/"), "路径要指明它在 fat jar 里的哪一层");
    }

    @Test
    @DisplayName("🔴 shade 进来的 jackson:类被打进宿主 jar,依赖坐标看不见,但 META-INF 还在")
    void shadedIntoHostJar(@TempDir Path dir) throws IOException {
        Map<String, String> m = pomProps(CveTable.GROUP_2X, "2.13.0");
        m.put("com/example/App.class", "x");
        m.put("META-INF/maven/com.example/my-app/pom.properties",
                "artifactId=my-app\ngroupId=com.example\nversion=1.0\n");
        Scanner s = scan(dir, "my-app-1.0-shaded.jar", zip(m));
        assertEquals(1, s.artifacts().size(), "读 pom 看不见,扫实物看得见");
        assertEquals("2.13.0", s.artifacts().get(0).version().toString());
    }

    @Test
    @DisplayName("🔴 路径分隔符写成 '\\' 的归档也要认(PowerShell Compress-Archive 就是一例)")
    void backslashEntries(@TempDir Path dir) throws IOException {
        Map<String, String> m = new LinkedHashMap<>();
        m.put("META-INF\\maven\\" + CveTable.GROUP_2X + "\\jackson-databind\\pom.properties",
                "artifactId=jackson-databind\ngroupId=" + CveTable.GROUP_2X + "\nversion=2.18.5\n");
        Scanner s = scan(dir, "weird.jar", zip(m));
        assertEquals(1, s.artifacts().size(), "「没扫到」和「你很安全」长得一模一样");
    }

    @Test
    @DisplayName("没有 pom.properties 时退回 MANIFEST 的 Bundle-SymbolicName(它带 groupId)")
    void fallbackToManifest(@TempDir Path dir) throws IOException {
        Map<String, String> m = new LinkedHashMap<>();
        m.put("META-INF/MANIFEST.MF", "Manifest-Version: 1.0\r\n"
                + "Bundle-SymbolicName: " + CveTable.GROUP_3X + ".jackson-databind\r\n"
                + "Bundle-Version: 3.1.2\r\n\r\n");
        Scanner s = scan(dir, "repacked.jar", zip(m));
        assertEquals(1, s.artifacts().size());
        assertEquals(CveTable.GROUP_3X, s.artifacts().get(0).groupId());
        assertEquals("MANIFEST", s.artifacts().get(0).source());
        assertFalse(s.artifacts().get(0).guessedGroup(), "Bundle-SymbolicName 里有 groupId,不算推断");
    }

    @Test
    @DisplayName("只剩文件名时按大版本推断 groupId,并且必须打上「推断」标记")
    void fallbackToFileNameIsMarkedAsGuess(@TempDir Path dir) throws IOException {
        Map<String, String> m = new LinkedHashMap<>();
        m.put("tools/jackson/databind/ObjectMapper.class", "x");
        Scanner s = scan(dir, "jackson-databind-3.1.2.jar", zip(m));
        assertEquals(1, s.artifacts().size());
        assertEquals(CveTable.GROUP_3X, s.artifacts().get(0).groupId());
        assertTrue(s.artifacts().get(0).guessedGroup(), "文件名里没有 groupId —— 是推断,报告要说出来");
    }

    @Test
    @DisplayName("同名的第三方构件不能被误认成 jackson")
    void otherGroupIdIsIgnored(@TempDir Path dir) throws IOException {
        Scanner s = scan(dir, "x.jar", zip(pomProps("org.evil.fork", "2.18.5")));
        assertTrue(s.artifacts().isEmpty(), "只认那两个官方 groupId");
    }

    @Test
    @DisplayName("坏归档要告警,并且明说「这不等于里面没有 jackson」")
    void brokenArchiveWarns(@TempDir Path dir) throws IOException {
        Scanner s = scan(dir, "broken.jar", "this is not a zip".getBytes(StandardCharsets.UTF_8));
        assertTrue(s.artifacts().isEmpty());
        // 内容不是 zip 时 ZipInputStream 直接读不出条目,不一定抛异常 —— 关键是不能凭空报出构件
    }

    @Test
    @DisplayName("目录扫描:同一目录下两代 jar 都要扫到")
    void directoryWithTwoVersions(@TempDir Path dir) throws IOException {
        Files.createDirectories(dir.resolve("lib"));
        Files.write(dir.resolve("lib/a.jar"), zip(pomProps(CveTable.GROUP_2X, "2.13.0")));
        Files.write(dir.resolve("lib/b.jar"), zip(pomProps(CveTable.GROUP_2X, "2.21.2")));
        Scanner s = new Scanner();
        s.scan(dir);
        assertEquals(2, s.artifacts().size(), "老 WAR 里塞两代 jar 是真实存在的形态,漏一个就是漏报");
    }
}
