package dev.mikko.jacksoncheck;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

/**
 * 由 tools/gen_rules.py 从两个一手源生成,请勿手工编辑。
 * 源 A:/repos/FasterXML/jackson-databind/security-advisories(官方条目全集 + 描述原文)
 * 源 B:/advisories?ecosystem=maven&affects=&lt;坐标&gt;(Dependabot 实际用的坐标索引)
 *
 * <p>粒度是 <b>advisory × groupId × 版本区间</b>:Jackson 3 换了 groupId,
 * 同一条 advisory 在两个坐标、多条维护分支上的受影响区间和修复版都不同。
 */
public final class CveTable {
    private CveTable() {}

    public static final String GENERATED_FROM = "github.com/FasterXML/jackson-databind security advisories + GitHub Advisory API";

    /** Jackson 2.x 的坐标。 */
    public static final String GROUP_2X = "com.fasterxml.jackson.core";
    /** Jackson 3.x 的坐标 —— 换了 groupId,这是本工具必须覆盖两套坐标的原因。 */
    public static final String GROUP_3X = "tools.jackson.core";
    public static final String ARTIFACT = "jackson-databind";

    /** 官方发布的本批条目总数(用于报告里说明覆盖范围)。 */
    public static final int OFFICIAL_TOTAL = 15;

    /**
     * 官方发布了、但按两个坐标都查不到的条目数 —— 即进不了 Dependabot 告警的数量。
     *
     * <p>🔴 08-07 首版实测为 0;2026-09-14 重跑为 4(08-21 / 09-01 新发的 4 条全局库仍 404)。
     * 每条都逐个按 GHSA 号复核过,gen_rules.py 的 ASSERT2 每次重跑都会重新核实。
     */
    public static final int DEPENDABOT_BLIND = 4;

    private static final List<Cve> ALL = new ArrayList<>();

    static {
        add("GHSA-wjgm-6hv5-3cvf", "CVE-2026-19032", "tools.jackson.core", "medium", 5.3, "3.1", "3.0.0", true, "3.1.6", false, "3.1.6", true, "NIO_PATH_PROVIDER", "仅当把不可信 JSON 绑定到 java.nio.file.Path 字段;且只有 JDK 自带 provider 时结果无害,要真正产生副作用还需 classpath 上有第三方 FileSystemProvider", "NioPath,FS_PROVIDER", "Path Deserialization Missing Scheme Allowlist for FileSystemProvider Resolution", "A java.nio.file.Path field bound from untrusted JSON reaches JDKFromStringDeserializer.NioPathHelper.deserialize. The attacker string flows through new URI(value) → Path.of(uri), then on FileSystemNo…", false);
        add("GHSA-wjgm-6hv5-3cvf", "CVE-2026-19032", "tools.jackson.core", "medium", 5.3, "3.2", "3.2.0", true, "3.2.2", false, "3.2.2", true, "NIO_PATH_PROVIDER", "仅当把不可信 JSON 绑定到 java.nio.file.Path 字段;且只有 JDK 自带 provider 时结果无害,要真正产生副作用还需 classpath 上有第三方 FileSystemProvider", "NioPath,FS_PROVIDER", "Path Deserialization Missing Scheme Allowlist for FileSystemProvider Resolution", "A java.nio.file.Path field bound from untrusted JSON reaches JDKFromStringDeserializer.NioPathHelper.deserialize. The attacker string flows through new URI(value) → Path.of(uri), then on FileSystemNo…", false);
        add("GHSA-wjgm-6hv5-3cvf", "CVE-2026-19032", "com.fasterxml.jackson.core", "medium", 5.3, "2.18", "2.8.0", true, "2.18.10", false, "2.18.10", true, "NIO_PATH_PROVIDER", "仅当把不可信 JSON 绑定到 java.nio.file.Path 字段;且只有 JDK 自带 provider 时结果无害,要真正产生副作用还需 classpath 上有第三方 FileSystemProvider", "NioPath,FS_PROVIDER", "Path Deserialization Missing Scheme Allowlist for FileSystemProvider Resolution", "A java.nio.file.Path field bound from untrusted JSON reaches JDKFromStringDeserializer.NioPathHelper.deserialize. The attacker string flows through new URI(value) → Path.of(uri), then on FileSystemNo…", false);
        add("GHSA-wjgm-6hv5-3cvf", "CVE-2026-19032", "com.fasterxml.jackson.core", "medium", 5.3, "2.21", "2.19.0", true, "2.21.6", false, "2.21.6", true, "NIO_PATH_PROVIDER", "仅当把不可信 JSON 绑定到 java.nio.file.Path 字段;且只有 JDK 自带 provider 时结果无害,要真正产生副作用还需 classpath 上有第三方 FileSystemProvider", "NioPath,FS_PROVIDER", "Path Deserialization Missing Scheme Allowlist for FileSystemProvider Resolution", "A java.nio.file.Path field bound from untrusted JSON reaches JDKFromStringDeserializer.NioPathHelper.deserialize. The attacker string flows through new URI(value) → Path.of(uri), then on FileSystemNo…", false);
        add("GHSA-wjgm-6hv5-3cvf", "CVE-2026-19032", "com.fasterxml.jackson.core", "medium", 5.3, "2.22", "2.22.0", true, "2.22.2", false, "2.22.2", true, "NIO_PATH_PROVIDER", "仅当把不可信 JSON 绑定到 java.nio.file.Path 字段;且只有 JDK 自带 provider 时结果无害,要真正产生副作用还需 classpath 上有第三方 FileSystemProvider", "NioPath,FS_PROVIDER", "Path Deserialization Missing Scheme Allowlist for FileSystemProvider Resolution", "A java.nio.file.Path field bound from untrusted JSON reaches JDKFromStringDeserializer.NioPathHelper.deserialize. The attacker string flows through new URI(value) → Path.of(uri), then on FileSystemNo…", false);
        add("GHSA-3wrr-7qpf-2prh", "CVE-2026-50193", "com.fasterxml.jackson.core", "medium", 7.5, "2.14", "2.10.0", true, "2.13.5", true, "2.14.0", true, "JSONNODE_TOSTRING", "仅当用 ObjectMapper.readTree() 读入深层嵌套 JSON,再用 JsonNode.toString() 输出", "readTree,JsonNode", "Deeply nested JsonNode throws StackOverflowError for toString()", "Potential Denial-of-Service when attacker sends deeply nested JSON if (and only if) service:", true);
        add("GHSA-j3rv-43j4-c7qm", "CVE-2026-54512", "com.fasterxml.jackson.core", "high", 8.1, "2.18", "2.10.0", true, "2.18.7", true, "2.18.8", true, "POLYMORPHIC", "仅当开启了多态类型(@JsonTypeInfo 或 activateDefaultTyping)且配置了 PolymorphicTypeValidator,并且攻击者能控制 type id 字符串", "@JsonTypeInfo,PolymorphicTypeValidator", "PolymorphicTypeValidator bypass via generic type parameters in jackson-databind allows arbitrary…", "jackson-databind's PolymorphicTypeValidator (PTV) is the primary safety mechanism guarding polymorphic deserialization. When polymorphic typing is enabled and a type identifier contains generic param…", true);
        add("GHSA-j3rv-43j4-c7qm", "CVE-2026-54512", "com.fasterxml.jackson.core", "high", 8.1, "3.1", "3.0.0", true, "3.1.3", true, "3.1.4", false, "POLYMORPHIC", "仅当开启了多态类型(@JsonTypeInfo 或 activateDefaultTyping)且配置了 PolymorphicTypeValidator,并且攻击者能控制 type id 字符串", "@JsonTypeInfo,PolymorphicTypeValidator", "PolymorphicTypeValidator bypass via generic type parameters in jackson-databind allows arbitrary…", "jackson-databind's PolymorphicTypeValidator (PTV) is the primary safety mechanism guarding polymorphic deserialization. When polymorphic typing is enabled and a type identifier contains generic param…", true);
        add("GHSA-j3rv-43j4-c7qm", "CVE-2026-54512", "com.fasterxml.jackson.core", "high", 8.1, "2.21", "2.19.0", true, "2.21.3", true, "2.21.4", true, "POLYMORPHIC", "仅当开启了多态类型(@JsonTypeInfo 或 activateDefaultTyping)且配置了 PolymorphicTypeValidator,并且攻击者能控制 type id 字符串", "@JsonTypeInfo,PolymorphicTypeValidator", "PolymorphicTypeValidator bypass via generic type parameters in jackson-databind allows arbitrary…", "jackson-databind's PolymorphicTypeValidator (PTV) is the primary safety mechanism guarding polymorphic deserialization. When polymorphic typing is enabled and a type identifier contains generic param…", true);
        add("GHSA-j3rv-43j4-c7qm", "CVE-2026-54512", "tools.jackson.core", "high", 8.1, "3.1", "3.0.0", true, "3.1.3", true, "3.1.4", true, "POLYMORPHIC", "仅当开启了多态类型(@JsonTypeInfo 或 activateDefaultTyping)且配置了 PolymorphicTypeValidator,并且攻击者能控制 type id 字符串", "@JsonTypeInfo,PolymorphicTypeValidator", "PolymorphicTypeValidator bypass via generic type parameters in jackson-databind allows arbitrary…", "jackson-databind's PolymorphicTypeValidator (PTV) is the primary safety mechanism guarding polymorphic deserialization. When polymorphic typing is enabled and a type identifier contains generic param…", true);
        add("GHSA-rmj7-2vxq-3g9f", "CVE-2026-54513", "com.fasterxml.jackson.core", "high", 8.1, "2.18", "2.10.0", true, "2.18.8", false, "2.18.8", true, "POLYMORPHIC_ARRAY", "仅当用 BasicPolymorphicTypeValidator 且调用了 allowIfSubTypeIsArray() 来放行数组类型", "PolymorphicTypeValidator,allowIfSubTypeIsArray", "Array subtype allowlist bypass in BasicPolymorphicTypeValidator (allowIfSubTypeIsArray) in…", "BasicPolymorphicTypeValidator.Builder.allowIfSubTypeIsArray() allowlists any array type based only on clazz.isArray(), without validating the array's component (element) type against the configured a…", true);
        add("GHSA-rmj7-2vxq-3g9f", "CVE-2026-54513", "com.fasterxml.jackson.core", "high", 8.1, "2.21", "2.19.0", true, "2.21.4", false, "2.21.4", true, "POLYMORPHIC_ARRAY", "仅当用 BasicPolymorphicTypeValidator 且调用了 allowIfSubTypeIsArray() 来放行数组类型", "PolymorphicTypeValidator,allowIfSubTypeIsArray", "Array subtype allowlist bypass in BasicPolymorphicTypeValidator (allowIfSubTypeIsArray) in…", "BasicPolymorphicTypeValidator.Builder.allowIfSubTypeIsArray() allowlists any array type based only on clazz.isArray(), without validating the array's component (element) type against the configured a…", true);
        add("GHSA-rmj7-2vxq-3g9f", "CVE-2026-54513", "com.fasterxml.jackson.core", "high", 8.1, "3.1", "3.0.0", true, "3.1.4", false, "3.1.4", false, "POLYMORPHIC_ARRAY", "仅当用 BasicPolymorphicTypeValidator 且调用了 allowIfSubTypeIsArray() 来放行数组类型", "PolymorphicTypeValidator,allowIfSubTypeIsArray", "Array subtype allowlist bypass in BasicPolymorphicTypeValidator (allowIfSubTypeIsArray) in…", "BasicPolymorphicTypeValidator.Builder.allowIfSubTypeIsArray() allowlists any array type based only on clazz.isArray(), without validating the array's component (element) type against the configured a…", true);
        add("GHSA-rmj7-2vxq-3g9f", "CVE-2026-54513", "tools.jackson.core", "high", 8.1, "3.1", "3.0.0", true, "3.1.4", false, "3.1.4", true, "POLYMORPHIC_ARRAY", "仅当用 BasicPolymorphicTypeValidator 且调用了 allowIfSubTypeIsArray() 来放行数组类型", "PolymorphicTypeValidator,allowIfSubTypeIsArray", "Array subtype allowlist bypass in BasicPolymorphicTypeValidator (allowIfSubTypeIsArray) in…", "BasicPolymorphicTypeValidator.Builder.allowIfSubTypeIsArray() allowlists any array type based only on clazz.isArray(), without validating the array's component (element) type against the configured a…", true);
        add("GHSA-hgj6-7826-r7m5", "CVE-2026-54514", "com.fasterxml.jackson.core", "medium", 5.3, "2.18", "2.0.0", true, "2.18.8", false, "2.18.8", true, "INET_SOCKET_ADDRESS", "仅当把不可信 JSON 绑定到含 InetSocketAddress 字段的类型上(绑定时就会发起 DNS 查询)", "InetSocketAddress", "InetSocketAddress deserialization triggers eager DNS resolution (SSRF) in jackson-databind", "JDKFromStringDeserializer constructed InetSocketAddress with new InetSocketAddress(host, port), which performs eager DNS name resolution for hostname inputs at deserialization time. An application th…", true);
        add("GHSA-hgj6-7826-r7m5", "CVE-2026-54514", "com.fasterxml.jackson.core", "medium", 5.3, "2.21", "2.19.0", true, "2.21.4", false, "2.21.4", true, "INET_SOCKET_ADDRESS", "仅当把不可信 JSON 绑定到含 InetSocketAddress 字段的类型上(绑定时就会发起 DNS 查询)", "InetSocketAddress", "InetSocketAddress deserialization triggers eager DNS resolution (SSRF) in jackson-databind", "JDKFromStringDeserializer constructed InetSocketAddress with new InetSocketAddress(host, port), which performs eager DNS name resolution for hostname inputs at deserialization time. An application th…", true);
        add("GHSA-hgj6-7826-r7m5", "CVE-2026-54514", "com.fasterxml.jackson.core", "medium", 5.3, "3.1", "3.0.0", true, "3.1.4", false, "3.1.4", false, "INET_SOCKET_ADDRESS", "仅当把不可信 JSON 绑定到含 InetSocketAddress 字段的类型上(绑定时就会发起 DNS 查询)", "InetSocketAddress", "InetSocketAddress deserialization triggers eager DNS resolution (SSRF) in jackson-databind", "JDKFromStringDeserializer constructed InetSocketAddress with new InetSocketAddress(host, port), which performs eager DNS name resolution for hostname inputs at deserialization time. An application th…", true);
        add("GHSA-hgj6-7826-r7m5", "CVE-2026-54514", "tools.jackson.core", "medium", 5.3, "2.21", "2.19.0", true, "2.21.4", false, "2.21.4", false, "INET_SOCKET_ADDRESS", "仅当把不可信 JSON 绑定到含 InetSocketAddress 字段的类型上(绑定时就会发起 DNS 查询)", "InetSocketAddress", "InetSocketAddress deserialization triggers eager DNS resolution (SSRF) in jackson-databind", "JDKFromStringDeserializer constructed InetSocketAddress with new InetSocketAddress(host, port), which performs eager DNS name resolution for hostname inputs at deserialization time. An application th…", true);
        add("GHSA-hgj6-7826-r7m5", "CVE-2026-54514", "tools.jackson.core", "medium", 5.3, "3.1", "3.0.0", true, "3.1.4", false, "3.1.4", true, "INET_SOCKET_ADDRESS", "仅当把不可信 JSON 绑定到含 InetSocketAddress 字段的类型上(绑定时就会发起 DNS 查询)", "InetSocketAddress", "InetSocketAddress deserialization triggers eager DNS resolution (SSRF) in jackson-databind", "JDKFromStringDeserializer constructed InetSocketAddress with new InetSocketAddress(host, port), which performs eager DNS name resolution for hostname inputs at deserialization time. An application th…", true);
        add("GHSA-5jmj-h7xm-6q6v", "CVE-2026-54515", "com.fasterxml.jackson.core", "medium", 5.3, "3.1", "3.1.0", true, "3.1.4", false, "3.1.4", false, "CASE_INSENSITIVE", "仅当同时开启了大小写不敏感匹配(@JsonFormat 的 ACCEPT_CASE_INSENSITIVE_PROPERTIES)并依赖逐属性的 @JsonIgnoreProperties 把字段挡在外面", "ACCEPT_CASE_INSENSITIVE_PROPERTIES,@JsonIgnoreProperties", "Case-insensitive deserialization bypasses per-property @JsonIgnoreProperties in jackson-databind", "In BeanDeserializerBase.createContextual(), per-property @JsonIgnoreProperties exclusions are applied by _handleByNameInclusion(), producing a contextual deserializer whose BeanPropertyMap has the ig…", true);
        add("GHSA-5jmj-h7xm-6q6v", "CVE-2026-54515", "tools.jackson.core", "medium", 5.3, "3.1", "3.1.0", true, "3.1.4", false, "3.1.4", true, "CASE_INSENSITIVE", "仅当同时开启了大小写不敏感匹配(@JsonFormat 的 ACCEPT_CASE_INSENSITIVE_PROPERTIES)并依赖逐属性的 @JsonIgnoreProperties 把字段挡在外面", "ACCEPT_CASE_INSENSITIVE_PROPERTIES,@JsonIgnoreProperties", "Case-insensitive deserialization bypasses per-property @JsonIgnoreProperties in jackson-databind", "In BeanDeserializerBase.createContextual(), per-property @JsonIgnoreProperties exclusions are applied by _handleByNameInclusion(), producing a contextual deserializer whose BeanPropertyMap has the ig…", true);
        add("GHSA-5jmj-h7xm-6q6v", "CVE-2026-54515", "com.fasterxml.jackson.core", "medium", 5.3, "2.18", "2.8.0", true, "2.18.9", false, "2.18.9", true, "CASE_INSENSITIVE", "仅当同时开启了大小写不敏感匹配(@JsonFormat 的 ACCEPT_CASE_INSENSITIVE_PROPERTIES)并依赖逐属性的 @JsonIgnoreProperties 把字段挡在外面", "ACCEPT_CASE_INSENSITIVE_PROPERTIES,@JsonIgnoreProperties", "Case-insensitive deserialization bypasses per-property @JsonIgnoreProperties in jackson-databind", "In BeanDeserializerBase.createContextual(), per-property @JsonIgnoreProperties exclusions are applied by _handleByNameInclusion(), producing a contextual deserializer whose BeanPropertyMap has the ig…", true);
        add("GHSA-5jmj-h7xm-6q6v", "CVE-2026-54515", "com.fasterxml.jackson.core", "medium", 5.3, "2.21", "2.19.0", true, "2.21.5", false, "2.21.5", true, "CASE_INSENSITIVE", "仅当同时开启了大小写不敏感匹配(@JsonFormat 的 ACCEPT_CASE_INSENSITIVE_PROPERTIES)并依赖逐属性的 @JsonIgnoreProperties 把字段挡在外面", "ACCEPT_CASE_INSENSITIVE_PROPERTIES,@JsonIgnoreProperties", "Case-insensitive deserialization bypasses per-property @JsonIgnoreProperties in jackson-databind", "In BeanDeserializerBase.createContextual(), per-property @JsonIgnoreProperties exclusions are applied by _handleByNameInclusion(), producing a contextual deserializer whose BeanPropertyMap has the ig…", true);
        add("GHSA-5jmj-h7xm-6q6v", "CVE-2026-54515", "com.fasterxml.jackson.core", "medium", 5.3, "2.22", "2.22.0", true, "2.22.1", false, "2.22.1", true, "CASE_INSENSITIVE", "仅当同时开启了大小写不敏感匹配(@JsonFormat 的 ACCEPT_CASE_INSENSITIVE_PROPERTIES)并依赖逐属性的 @JsonIgnoreProperties 把字段挡在外面", "ACCEPT_CASE_INSENSITIVE_PROPERTIES,@JsonIgnoreProperties", "Case-insensitive deserialization bypasses per-property @JsonIgnoreProperties in jackson-databind", "In BeanDeserializerBase.createContextual(), per-property @JsonIgnoreProperties exclusions are applied by _handleByNameInclusion(), producing a contextual deserializer whose BeanPropertyMap has the ig…", true);
        add("GHSA-9fxm-vc8v-hj55", "CVE-2026-54516", "com.fasterxml.jackson.core", "medium", 5.3, "2.21", "2.21.0", true, "2.21.4", false, "2.21.4", true, "IGNORED_SETTER_RENAME", "仅当同一个属性上 getter 带 @JsonProperty 改了名、setter 带 @JsonIgnore(即「只读不写」的写法)", "@JsonIgnore,@JsonProperty", "Renamed @JsonIgnore'd setters can deserialize via private fields in jackson-databind", "POJOPropertiesCollector._renameProperties() allows a property with @JsonProperty(\"renamed\") on the getter and @JsonIgnore on the setter to be renamed rather than dropped. With MapperFeature.INFER_PRO…", true);
        add("GHSA-9fxm-vc8v-hj55", "CVE-2026-54516", "com.fasterxml.jackson.core", "medium", 5.3, "3.1", "3.0.0", true, "3.1.4", false, "3.1.4", false, "IGNORED_SETTER_RENAME", "仅当同一个属性上 getter 带 @JsonProperty 改了名、setter 带 @JsonIgnore(即「只读不写」的写法)", "@JsonIgnore,@JsonProperty", "Renamed @JsonIgnore'd setters can deserialize via private fields in jackson-databind", "POJOPropertiesCollector._renameProperties() allows a property with @JsonProperty(\"renamed\") on the getter and @JsonIgnore on the setter to be renamed rather than dropped. With MapperFeature.INFER_PRO…", true);
        add("GHSA-9fxm-vc8v-hj55", "CVE-2026-54516", "tools.jackson.core", "medium", 5.3, "3.1", "3.0.0", true, "3.1.4", false, "3.1.4", true, "IGNORED_SETTER_RENAME", "仅当同一个属性上 getter 带 @JsonProperty 改了名、setter 带 @JsonIgnore(即「只读不写」的写法)", "@JsonIgnore,@JsonProperty", "Renamed @JsonIgnore'd setters can deserialize via private fields in jackson-databind", "POJOPropertiesCollector._renameProperties() allows a property with @JsonProperty(\"renamed\") on the getter and @JsonIgnore on the setter to be renamed rather than dropped. With MapperFeature.INFER_PRO…", true);
        add("GHSA-5hh8-q8hv-fr38", "CVE-2026-54517", "com.fasterxml.jackson.core", "medium", 5.3, "2.21", "2.21.0", true, "2.21.4", false, "2.21.4", true, "JSONVIEW", "仅当用 @JsonView 做写入侧权限门控,且被门控的是 setterless 的 Collection/Map 属性", "@JsonView", "@JsonView bypass for setterless creator properties in jackson-databind", "In BeanDeserializer._deserializeUsingPropertyBased, the active-view (@JsonView) filter was applied only to creator properties; the regular property-buffering branch performed no prop.visibleInView(ac…", true);
        add("GHSA-5hh8-q8hv-fr38", "CVE-2026-54517", "com.fasterxml.jackson.core", "medium", 5.3, "3.1", "3.0.0", true, "3.1.4", false, "3.1.4", false, "JSONVIEW", "仅当用 @JsonView 做写入侧权限门控,且被门控的是 setterless 的 Collection/Map 属性", "@JsonView", "@JsonView bypass for setterless creator properties in jackson-databind", "In BeanDeserializer._deserializeUsingPropertyBased, the active-view (@JsonView) filter was applied only to creator properties; the regular property-buffering branch performed no prop.visibleInView(ac…", true);
        add("GHSA-5hh8-q8hv-fr38", "CVE-2026-54517", "tools.jackson.core", "medium", 5.3, "3.1", "3.0.0", true, "3.1.4", false, "3.1.4", true, "JSONVIEW", "仅当用 @JsonView 做写入侧权限门控,且被门控的是 setterless 的 Collection/Map 属性", "@JsonView", "@JsonView bypass for setterless creator properties in jackson-databind", "In BeanDeserializer._deserializeUsingPropertyBased, the active-view (@JsonView) filter was applied only to creator properties; the regular property-buffering branch performed no prop.visibleInView(ac…", true);
        add("GHSA-rcqc-6cw3-h962", "CVE-2026-54518", "com.fasterxml.jackson.core", "medium", 6.5, "2.21", "2.21.0", true, "2.21.4", false, "2.21.4", true, "JSONVIEW_UNWRAPPED", "仅当 @JsonView 与 @JsonUnwrapped 同时标在构造器(creator)参数上", "@JsonView,@JsonUnwrapped", "@JsonView bypass for unwrapped creator parameters in jackson-databind", "UnwrappedPropertyHandler.processUnwrappedCreatorProperties() replays buffered JSON into creator parameters but never consults prop.visibleInView(activeView). The normal property-based creator path ga…", true);
        add("GHSA-rcqc-6cw3-h962", "CVE-2026-54518", "tools.jackson.core", "medium", 6.5, "3.1", "3.0.0", true, "3.1.4", false, "3.1.4", true, "JSONVIEW_UNWRAPPED", "仅当 @JsonView 与 @JsonUnwrapped 同时标在构造器(creator)参数上", "@JsonView,@JsonUnwrapped", "@JsonView bypass for unwrapped creator parameters in jackson-databind", "UnwrappedPropertyHandler.processUnwrappedCreatorProperties() replays buffered JSON into creator parameters but never consults prop.visibleInView(activeView). The normal property-based creator path ga…", true);
        add("GHSA-3pjw-73gf-8qr5", "CVE-2026-59888", "com.fasterxml.jackson.core", "medium", 6.5, "2.18", "2.15.0", true, "2.18.8", false, "2.18.8", true, "RECORD_NAMING", "仅当用 Java Record + PropertyNamingStrategy(命名策略),且靠 @JsonIgnore 挡住某个组件", "record,PropertyNamingStrategy,@JsonIgnore", "`@JsonIgnore` on a Record property is bypassed with a PropertyNamingStrategy in jackson-databind…", "For Java Records, POJOPropertiesCollector._removeUnwantedIgnorals() records a @JsonIgnore-annotated component under its original implicit name before _renameUsing() applies the PropertyNamingStrategy…", true);
        add("GHSA-3pjw-73gf-8qr5", "CVE-2026-59888", "com.fasterxml.jackson.core", "medium", 6.5, "2.21", "2.19.0", true, "2.21.4", false, "2.21.4", true, "RECORD_NAMING", "仅当用 Java Record + PropertyNamingStrategy(命名策略),且靠 @JsonIgnore 挡住某个组件", "record,PropertyNamingStrategy,@JsonIgnore", "`@JsonIgnore` on a Record property is bypassed with a PropertyNamingStrategy in jackson-databind…", "For Java Records, POJOPropertiesCollector._removeUnwantedIgnorals() records a @JsonIgnore-annotated component under its original implicit name before _renameUsing() applies the PropertyNamingStrategy…", true);
        add("GHSA-3pjw-73gf-8qr5", "CVE-2026-59888", "tools.jackson.core", "medium", 6.5, "3.1", "3.0.0", true, "3.1.4", false, "3.1.4", true, "RECORD_NAMING", "仅当用 Java Record + PropertyNamingStrategy(命名策略),且靠 @JsonIgnore 挡住某个组件", "record,PropertyNamingStrategy,@JsonIgnore", "`@JsonIgnore` on a Record property is bypassed with a PropertyNamingStrategy in jackson-databind…", "For Java Records, POJOPropertiesCollector._removeUnwantedIgnorals() records a @JsonIgnore-annotated component under its original implicit name before _renameUsing() applies the PropertyNamingStrategy…", true);
        add("GHSA-5gvw-p9qm-jgwh", "CVE-2026-59889", "com.fasterxml.jackson.core", "medium", 6.5, "2.21", "2.21.0", true, "2.21.5", false, "2.21.5", true, "JSONVIEW_UNWRAPPED", "仅当同一个属性上同时有 @JsonView 和 @JsonUnwrapped(容器属性,非构造器参数)", "@JsonView,@JsonUnwrapped", "@JsonView bypassed for @JsonUnwrapped container properties on deserialization: a…", "UnwrappedPropertyHandler.processUnwrapped() replays the buffered JSON for a @JsonUnwrapped property by iterating its properties and calling prop.deserializeAndSet() with no prop.visibleInView(ctxt.ge…", true);
        add("GHSA-5gvw-p9qm-jgwh", "CVE-2026-59889", "tools.jackson.core", "medium", 6.5, "3.1", "3.0.0", true, "3.1.4", true, "3.1.5", true, "JSONVIEW_UNWRAPPED", "仅当同一个属性上同时有 @JsonView 和 @JsonUnwrapped(容器属性,非构造器参数)", "@JsonView,@JsonUnwrapped", "@JsonView bypassed for @JsonUnwrapped container properties on deserialization: a…", "UnwrappedPropertyHandler.processUnwrapped() replays the buffered JSON for a @JsonUnwrapped property by iterating its properties and calling prop.deserializeAndSet() with no prop.visibleInView(ctxt.ge…", true);
        add("GHSA-5gvw-p9qm-jgwh", "CVE-2026-59889", "com.fasterxml.jackson.core", "medium", 6.5, "2.18", "2.18.0", true, "2.18.8", true, "2.18.9", true, "JSONVIEW_UNWRAPPED", "仅当同一个属性上同时有 @JsonView 和 @JsonUnwrapped(容器属性,非构造器参数)", "@JsonView,@JsonUnwrapped", "@JsonView bypassed for @JsonUnwrapped container properties on deserialization: a…", "UnwrappedPropertyHandler.processUnwrapped() replays the buffered JSON for a @JsonUnwrapped property by iterating its properties and calling prop.deserializeAndSet() with no prop.visibleInView(ctxt.ge…", true);
        add("GHSA-5gvw-p9qm-jgwh", "CVE-2026-59889", "com.fasterxml.jackson.core", "medium", 6.5, "2.22", "2.22.0", true, "2.22.1", false, "2.22.1", true, "JSONVIEW_UNWRAPPED", "仅当同一个属性上同时有 @JsonView 和 @JsonUnwrapped(容器属性,非构造器参数)", "@JsonView,@JsonUnwrapped", "@JsonView bypassed for @JsonUnwrapped container properties on deserialization: a…", "UnwrappedPropertyHandler.processUnwrapped() replays the buffered JSON for a @JsonUnwrapped property by iterating its properties and calling prop.deserializeAndSet() with no prop.visibleInView(ctxt.ge…", true);
        add("GHSA-5gvw-p9qm-jgwh", "CVE-2026-59889", "tools.jackson.core", "medium", 6.5, "3.2", "3.2.0", true, "3.2.1", false, "3.2.1", true, "JSONVIEW_UNWRAPPED", "仅当同一个属性上同时有 @JsonView 和 @JsonUnwrapped(容器属性,非构造器参数)", "@JsonView,@JsonUnwrapped", "@JsonView bypassed for @JsonUnwrapped container properties on deserialization: a…", "UnwrappedPropertyHandler.processUnwrapped() replays the buffered JSON for a @JsonUnwrapped property by iterating its properties and calling prop.deserializeAndSet() with no prop.visibleInView(ctxt.ge…", true);
        add("GHSA-q4xh-88c3-wmh7", "CVE-2026-68497", "tools.jackson.core", "high", 7.5, "3.2", "3.2.0", true, "3.2.2", false, "3.2.2", true, "XML_DATATYPE", "仅当把不可信 JSON 绑定到 javax.xml.datatype.Duration 或 XMLGregorianCalendar 类型的字段(默认 mapper 即可,不需要多态或特殊配置;注意 java.time.Duration 不是这一条)", "XMLDatatype", "Duration XMLGregorianCalendar Unbounded Number Parse DoS", "jackson-databind 3.2.1 deserializes a JSON string bound to a javax.xml.datatype.Duration or javax.xml.datatype.XMLGregorianCalendar field by passing the raw string verbatim to DatatypeFactory.newDura…", false);
        add("GHSA-q4xh-88c3-wmh7", "CVE-2026-68497", "tools.jackson.core", "high", 7.5, "3.1", "3.0.0", true, "3.1.6", false, "3.1.6", true, "XML_DATATYPE", "仅当把不可信 JSON 绑定到 javax.xml.datatype.Duration 或 XMLGregorianCalendar 类型的字段(默认 mapper 即可,不需要多态或特殊配置;注意 java.time.Duration 不是这一条)", "XMLDatatype", "Duration XMLGregorianCalendar Unbounded Number Parse DoS", "jackson-databind 3.2.1 deserializes a JSON string bound to a javax.xml.datatype.Duration or javax.xml.datatype.XMLGregorianCalendar field by passing the raw string verbatim to DatatypeFactory.newDura…", false);
        add("GHSA-q4xh-88c3-wmh7", "CVE-2026-68497", "com.fasterxml.jackson.core", "high", 7.5, "2.18", "2.14.0", true, "2.18.10", false, "2.18.10", true, "XML_DATATYPE", "仅当把不可信 JSON 绑定到 javax.xml.datatype.Duration 或 XMLGregorianCalendar 类型的字段(默认 mapper 即可,不需要多态或特殊配置;注意 java.time.Duration 不是这一条)", "XMLDatatype", "Duration XMLGregorianCalendar Unbounded Number Parse DoS", "jackson-databind 3.2.1 deserializes a JSON string bound to a javax.xml.datatype.Duration or javax.xml.datatype.XMLGregorianCalendar field by passing the raw string verbatim to DatatypeFactory.newDura…", false);
        add("GHSA-q4xh-88c3-wmh7", "CVE-2026-68497", "com.fasterxml.jackson.core", "high", 7.5, "2.21", "2.19.0", true, "2.21.6", false, "2.21.6", true, "XML_DATATYPE", "仅当把不可信 JSON 绑定到 javax.xml.datatype.Duration 或 XMLGregorianCalendar 类型的字段(默认 mapper 即可,不需要多态或特殊配置;注意 java.time.Duration 不是这一条)", "XMLDatatype", "Duration XMLGregorianCalendar Unbounded Number Parse DoS", "jackson-databind 3.2.1 deserializes a JSON string bound to a javax.xml.datatype.Duration or javax.xml.datatype.XMLGregorianCalendar field by passing the raw string verbatim to DatatypeFactory.newDura…", false);
        add("GHSA-q4xh-88c3-wmh7", "CVE-2026-68497", "com.fasterxml.jackson.core", "high", 7.5, "2.22", "2.22.0", true, "2.22.2", false, "2.22.2", true, "XML_DATATYPE", "仅当把不可信 JSON 绑定到 javax.xml.datatype.Duration 或 XMLGregorianCalendar 类型的字段(默认 mapper 即可,不需要多态或特殊配置;注意 java.time.Duration 不是这一条)", "XMLDatatype", "Duration XMLGregorianCalendar Unbounded Number Parse DoS", "jackson-databind 3.2.1 deserializes a JSON string bound to a javax.xml.datatype.Duration or javax.xml.datatype.XMLGregorianCalendar field by passing the raw string verbatim to DatatypeFactory.newDura…", false);
        add("GHSA-vvgp-rfg2-7rr6", "CVE-2026-77310", "com.fasterxml.jackson.core", "medium", 5.3, "2.18", "2.0.0", true, "2.18.9", false, "2.18.9", true, "INET_ADDRESS", "仅当把不可信 JSON 绑定到 InetAddress 类型(绑定时就会发起 DNS 查询)。这是 CVE-2026-54514(InetSocketAddress)修得不完整留下的兄弟分支", "InetAddress", "Incomplete fix for CVE-2026-54514: eager DNS resolution (SSRF) still present in InetAddress…", "CVE-2026-54514 (GHSA-hgj6-7826-r7m5) fixed an eager-DNS-resolution / SSRF issue in jackson-databind's deserialization of java.net.InetSocketAddress by switching to InetSocketAddress.createUnresolved(…", false);
        add("GHSA-vvgp-rfg2-7rr6", "CVE-2026-77310", "com.fasterxml.jackson.core", "medium", 5.3, "2.21", "2.19.0", true, "2.21.5", false, "2.21.5", true, "INET_ADDRESS", "仅当把不可信 JSON 绑定到 InetAddress 类型(绑定时就会发起 DNS 查询)。这是 CVE-2026-54514(InetSocketAddress)修得不完整留下的兄弟分支", "InetAddress", "Incomplete fix for CVE-2026-54514: eager DNS resolution (SSRF) still present in InetAddress…", "CVE-2026-54514 (GHSA-hgj6-7826-r7m5) fixed an eager-DNS-resolution / SSRF issue in jackson-databind's deserialization of java.net.InetSocketAddress by switching to InetSocketAddress.createUnresolved(…", false);
        add("GHSA-vvgp-rfg2-7rr6", "CVE-2026-77310", "com.fasterxml.jackson.core", "medium", 5.3, "2.22", "2.22.0", true, "2.22.1", false, "2.22.1", true, "INET_ADDRESS", "仅当把不可信 JSON 绑定到 InetAddress 类型(绑定时就会发起 DNS 查询)。这是 CVE-2026-54514(InetSocketAddress)修得不完整留下的兄弟分支", "InetAddress", "Incomplete fix for CVE-2026-54514: eager DNS resolution (SSRF) still present in InetAddress…", "CVE-2026-54514 (GHSA-hgj6-7826-r7m5) fixed an eager-DNS-resolution / SSRF issue in jackson-databind's deserialization of java.net.InetSocketAddress by switching to InetSocketAddress.createUnresolved(…", false);
        add("GHSA-vvgp-rfg2-7rr6", "CVE-2026-77310", "tools.jackson.core", "medium", 5.3, "3.1", "3.0.0", true, "3.1.5", false, "3.1.5", true, "INET_ADDRESS", "仅当把不可信 JSON 绑定到 InetAddress 类型(绑定时就会发起 DNS 查询)。这是 CVE-2026-54514(InetSocketAddress)修得不完整留下的兄弟分支", "InetAddress", "Incomplete fix for CVE-2026-54514: eager DNS resolution (SSRF) still present in InetAddress…", "CVE-2026-54514 (GHSA-hgj6-7826-r7m5) fixed an eager-DNS-resolution / SSRF issue in jackson-databind's deserialization of java.net.InetSocketAddress by switching to InetSocketAddress.createUnresolved(…", false);
        add("GHSA-vvgp-rfg2-7rr6", "CVE-2026-77310", "tools.jackson.core", "medium", 5.3, "3.2", "3.2.0", true, "3.2.1", false, "3.2.1", true, "INET_ADDRESS", "仅当把不可信 JSON 绑定到 InetAddress 类型(绑定时就会发起 DNS 查询)。这是 CVE-2026-54514(InetSocketAddress)修得不完整留下的兄弟分支", "InetAddress", "Incomplete fix for CVE-2026-54514: eager DNS resolution (SSRF) still present in InetAddress…", "CVE-2026-54514 (GHSA-hgj6-7826-r7m5) fixed an eager-DNS-resolution / SSRF issue in jackson-databind's deserialization of java.net.InetSocketAddress by switching to InetSocketAddress.createUnresolved(…", false);
        add("GHSA-gx83-3vf8-gh7j", "CVE-2026-83557", "tools.jackson.core", "medium", 5.6, "3.1", "3.0.0", true, "3.1.6", false, "3.1.6", true, "POLYMORPHIC_COMPARABLE", "仅当 @JsonTypeInfo 标在 Comparable 类型的属性上,且没有配置自定义 PolymorphicTypeValidator(activateDefaultTyping 必须传 validator,不受影响)", "@JsonTypeInfo,ComparableProp", "Comparable missing from DefaultBaseTypeLimitingValidator's unsafe base types (incomplete…", "DefaultBaseTypeLimitingValidator — the PolymorphicTypeValidator used automatically whenever @JsonTypeInfo is applied without an explicitly configured custom validator — denies polymorphic resolution …", false);
        add("GHSA-gx83-3vf8-gh7j", "CVE-2026-83557", "tools.jackson.core", "medium", 5.6, "3.2", "3.2.0", true, "3.2.2", false, "3.2.2", true, "POLYMORPHIC_COMPARABLE", "仅当 @JsonTypeInfo 标在 Comparable 类型的属性上,且没有配置自定义 PolymorphicTypeValidator(activateDefaultTyping 必须传 validator,不受影响)", "@JsonTypeInfo,ComparableProp", "Comparable missing from DefaultBaseTypeLimitingValidator's unsafe base types (incomplete…", "DefaultBaseTypeLimitingValidator — the PolymorphicTypeValidator used automatically whenever @JsonTypeInfo is applied without an explicitly configured custom validator — denies polymorphic resolution …", false);
        add("GHSA-gx83-3vf8-gh7j", "CVE-2026-83557", "com.fasterxml.jackson.core", "medium", 5.6, "2.18", "2.11.0", true, "2.18.10", false, "2.18.10", true, "POLYMORPHIC_COMPARABLE", "仅当 @JsonTypeInfo 标在 Comparable 类型的属性上,且没有配置自定义 PolymorphicTypeValidator(activateDefaultTyping 必须传 validator,不受影响)", "@JsonTypeInfo,ComparableProp", "Comparable missing from DefaultBaseTypeLimitingValidator's unsafe base types (incomplete…", "DefaultBaseTypeLimitingValidator — the PolymorphicTypeValidator used automatically whenever @JsonTypeInfo is applied without an explicitly configured custom validator — denies polymorphic resolution …", false);
        add("GHSA-gx83-3vf8-gh7j", "CVE-2026-83557", "com.fasterxml.jackson.core", "medium", 5.6, "2.21", "2.19.0", true, "2.21.6", false, "2.21.6", true, "POLYMORPHIC_COMPARABLE", "仅当 @JsonTypeInfo 标在 Comparable 类型的属性上,且没有配置自定义 PolymorphicTypeValidator(activateDefaultTyping 必须传 validator,不受影响)", "@JsonTypeInfo,ComparableProp", "Comparable missing from DefaultBaseTypeLimitingValidator's unsafe base types (incomplete…", "DefaultBaseTypeLimitingValidator — the PolymorphicTypeValidator used automatically whenever @JsonTypeInfo is applied without an explicitly configured custom validator — denies polymorphic resolution …", false);
        add("GHSA-gx83-3vf8-gh7j", "CVE-2026-83557", "com.fasterxml.jackson.core", "medium", 5.6, "2.22", "2.22.0", true, "2.22.2", false, "2.22.2", true, "POLYMORPHIC_COMPARABLE", "仅当 @JsonTypeInfo 标在 Comparable 类型的属性上,且没有配置自定义 PolymorphicTypeValidator(activateDefaultTyping 必须传 validator,不受影响)", "@JsonTypeInfo,ComparableProp", "Comparable missing from DefaultBaseTypeLimitingValidator's unsafe base types (incomplete…", "DefaultBaseTypeLimitingValidator — the PolymorphicTypeValidator used automatically whenever @JsonTypeInfo is applied without an explicitly configured custom validator — denies polymorphic resolution …", false);
        add("GHSA-mhm7-754m-9p8w", "", "com.fasterxml.jackson.core", "medium", 6.5, "2.18", "2.18.0", true, "2.18.8", true, "2.18.9", true, "JSONVIEW_EXTERNAL_TYPEID", "仅当构造器参数上同时有 @JsonView 和 @JsonTypeInfo(include = As.EXTERNAL_PROPERTY)", "@JsonView,@JsonTypeInfo,EXTERNAL_PROPERTY", "`@JsonView` bypass for creator properties with `@JsonTypeInfo(include=As.EXTERNAL_PROPERTY)`", "In BeanDeserializer.deserializeUsingPropertyBasedWithExternalTypeId, the active-view (@JsonView) filter was applied only to the regular bean-property branch; the creator-property branch performed no …", true);
        add("GHSA-mhm7-754m-9p8w", "", "com.fasterxml.jackson.core", "medium", 6.5, "2.21", "2.21.0", true, "2.21.4", true, "2.21.5", true, "JSONVIEW_EXTERNAL_TYPEID", "仅当构造器参数上同时有 @JsonView 和 @JsonTypeInfo(include = As.EXTERNAL_PROPERTY)", "@JsonView,@JsonTypeInfo,EXTERNAL_PROPERTY", "`@JsonView` bypass for creator properties with `@JsonTypeInfo(include=As.EXTERNAL_PROPERTY)`", "In BeanDeserializer.deserializeUsingPropertyBasedWithExternalTypeId, the active-view (@JsonView) filter was applied only to the regular bean-property branch; the creator-property branch performed no …", true);
    }

    private static void add(String ghsaId, String cveId, String groupId, String severity,
                            double cvss, String branch,
                            String low, boolean lowIncl, String high, boolean highIncl,
                            String fixedIn, boolean fixedAvailable,
                            String condKind, String condText, String markers,
                            String title, String desc, boolean inGlobalDb) {
        ALL.add(new Cve(ghsaId, cveId, groupId, severity, cvss, branch,
                        low, lowIncl, high, highIncl, fixedIn, fixedAvailable,
                        condKind, condText,
                        markers.isEmpty() ? List.of() : List.of(markers.split(",")),
                        title, desc, inGlobalDb));
    }

    public static List<Cve> all() { return Collections.unmodifiableList(ALL); }
}
