package dev.mikko.jacksoncheck;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

/**
 * 由 tools/gen_rules.py 从两个一手源生成,请勿手工编辑。
 * 源 A:/repos/FasterXML/jackson-databind/security-advisories(官方条目全集 + 描述原文)
 * 源 B:/advisories?ecosystem=maven&affects=&lt;坐标&gt;(Dependabot 实际用的坐标索引)
 *
 * <p>粒度是 <b>advisory × groupId × 版本区间</b>:Jackson 3 换了 groupId,
 * 同一条 advisory 在两个坐标、多条维护分支上的受影响区间和修复版都不同。
 */
public final class CveTable {
    private CveTable() {}

    public static final String GENERATED_FROM = "github.com/FasterXML/jackson-databind security advisories + GitHub Advisory API";

    /** Jackson 2.x 的坐标。 */
    public static final String GROUP_2X = "com.fasterxml.jackson.core";
    /** Jackson 3.x 的坐标 —— 换了 groupId,这是本工具必须覆盖两套坐标的原因。 */
    public static final String GROUP_3X = "tools.jackson.core";
    public static final String ARTIFACT = "jackson-databind";

    /** 官方发布的本批条目总数(用于报告里说明覆盖范围)。 */
    public static final int OFFICIAL_TOTAL = 11;

    /**
     * 官方发布了、但按两个坐标都查不到的条目数 —— 即进不了 Dependabot 告警的数量。
     *
     * <p>🔴 本注实测为 0。这是<b>查了两个源之后</b>的结论,不是只查一个源的默认值;
     * 第 8 注(shiro)用同样的方法比出来是 5 条。gen_rules.py 的 ASSERT2 每次重跑都会重新核实。
     */
    public static final int DEPENDABOT_BLIND = 0;

    private static final List<Cve> ALL = new ArrayList<>();

    static {
        add("GHSA-3wrr-7qpf-2prh", "CVE-2026-50193", "com.fasterxml.jackson.core", "medium", 7.5, "2.14", "2.10.0", true, "2.13.5", true, "2.14.0", true, "JSONNODE_TOSTRING", "仅当用 ObjectMapper.readTree() 读入深层嵌套 JSON,再用 JsonNode.toString() 输出", "readTree,JsonNode", "Deeply nested JsonNode throws StackOverflowError for toString()", "Potential Denial-of-Service when attacker sends deeply nested JSON if (and only if) service:");
        add("GHSA-j3rv-43j4-c7qm", "CVE-2026-54512", "com.fasterxml.jackson.core", "high", 8.1, "2.18", "2.10.0", true, "2.18.7", true, "2.18.8", true, "POLYMORPHIC", "仅当开启了多态类型(@JsonTypeInfo 或 activateDefaultTyping)且配置了 PolymorphicTypeValidator,并且攻击者能控制 type id 字符串", "@JsonTypeInfo,PolymorphicTypeValidator", "PolymorphicTypeValidator bypass via generic type parameters in jackson-databind allows arbitrary…", "jackson-databind's PolymorphicTypeValidator (PTV) is the primary safety mechanism guarding polymorphic deserialization. When polymorphic typing is enabled and a type identifier contains generic param…");
        add("GHSA-j3rv-43j4-c7qm", "CVE-2026-54512", "com.fasterxml.jackson.core", "high", 8.1, "3.1", "3.0.0", true, "3.1.3", true, "3.1.4", false, "POLYMORPHIC", "仅当开启了多态类型(@JsonTypeInfo 或 activateDefaultTyping)且配置了 PolymorphicTypeValidator,并且攻击者能控制 type id 字符串", "@JsonTypeInfo,PolymorphicTypeValidator", "PolymorphicTypeValidator bypass via generic type parameters in jackson-databind allows arbitrary…", "jackson-databind's PolymorphicTypeValidator (PTV) is the primary safety mechanism guarding polymorphic deserialization. When polymorphic typing is enabled and a type identifier contains generic param…");
        add("GHSA-j3rv-43j4-c7qm", "CVE-2026-54512", "com.fasterxml.jackson.core", "high", 8.1, "2.21", "2.19.0", true, "2.21.3", true, "2.21.4", true, "POLYMORPHIC", "仅当开启了多态类型(@JsonTypeInfo 或 activateDefaultTyping)且配置了 PolymorphicTypeValidator,并且攻击者能控制 type id 字符串", "@JsonTypeInfo,PolymorphicTypeValidator", "PolymorphicTypeValidator bypass via generic type parameters in jackson-databind allows arbitrary…", "jackson-databind's PolymorphicTypeValidator (PTV) is the primary safety mechanism guarding polymorphic deserialization. When polymorphic typing is enabled and a type identifier contains generic param…");
        add("GHSA-j3rv-43j4-c7qm", "CVE-2026-54512", "tools.jackson.core", "high", 8.1, "3.1", "3.0.0", true, "3.1.3", true, "3.1.4", true, "POLYMORPHIC", "仅当开启了多态类型(@JsonTypeInfo 或 activateDefaultTyping)且配置了 PolymorphicTypeValidator,并且攻击者能控制 type id 字符串", "@JsonTypeInfo,PolymorphicTypeValidator", "PolymorphicTypeValidator bypass via generic type parameters in jackson-databind allows arbitrary…", "jackson-databind's PolymorphicTypeValidator (PTV) is the primary safety mechanism guarding polymorphic deserialization. When polymorphic typing is enabled and a type identifier contains generic param…");
        add("GHSA-rmj7-2vxq-3g9f", "CVE-2026-54513", "com.fasterxml.jackson.core", "high", 8.1, "2.18", "2.10.0", true, "2.18.8", false, "2.18.8", true, "POLYMORPHIC_ARRAY", "仅当用 BasicPolymorphicTypeValidator 且调用了 allowIfSubTypeIsArray() 来放行数组类型", "PolymorphicTypeValidator,allowIfSubTypeIsArray", "Array subtype allowlist bypass in BasicPolymorphicTypeValidator (allowIfSubTypeIsArray) in…", "BasicPolymorphicTypeValidator.Builder.allowIfSubTypeIsArray() allowlists any array type based only on clazz.isArray(), without validating the array's component (element) type against the configured a…");
        add("GHSA-rmj7-2vxq-3g9f", "CVE-2026-54513", "com.fasterxml.jackson.core", "high", 8.1, "2.21", "2.19.0", true, "2.21.4", false, "2.21.4", true, "POLYMORPHIC_ARRAY", "仅当用 BasicPolymorphicTypeValidator 且调用了 allowIfSubTypeIsArray() 来放行数组类型", "PolymorphicTypeValidator,allowIfSubTypeIsArray", "Array subtype allowlist bypass in BasicPolymorphicTypeValidator (allowIfSubTypeIsArray) in…", "BasicPolymorphicTypeValidator.Builder.allowIfSubTypeIsArray() allowlists any array type based only on clazz.isArray(), without validating the array's component (element) type against the configured a…");
        add("GHSA-rmj7-2vxq-3g9f", "CVE-2026-54513", "com.fasterxml.jackson.core", "high", 8.1, "3.1", "3.0.0", true, "3.1.4", false, "3.1.4", false, "POLYMORPHIC_ARRAY", "仅当用 BasicPolymorphicTypeValidator 且调用了 allowIfSubTypeIsArray() 来放行数组类型", "PolymorphicTypeValidator,allowIfSubTypeIsArray", "Array subtype allowlist bypass in BasicPolymorphicTypeValidator (allowIfSubTypeIsArray) in…", "BasicPolymorphicTypeValidator.Builder.allowIfSubTypeIsArray() allowlists any array type based only on clazz.isArray(), without validating the array's component (element) type against the configured a…");
        add("GHSA-rmj7-2vxq-3g9f", "CVE-2026-54513", "tools.jackson.core", "high", 8.1, "3.1", "3.0.0", true, "3.1.4", false, "3.1.4", true, "POLYMORPHIC_ARRAY", "仅当用 BasicPolymorphicTypeValidator 且调用了 allowIfSubTypeIsArray() 来放行数组类型", "PolymorphicTypeValidator,allowIfSubTypeIsArray", "Array subtype allowlist bypass in BasicPolymorphicTypeValidator (allowIfSubTypeIsArray) in…", "BasicPolymorphicTypeValidator.Builder.allowIfSubTypeIsArray() allowlists any array type based only on clazz.isArray(), without validating the array's component (element) type against the configured a…");
        add("GHSA-hgj6-7826-r7m5", "CVE-2026-54514", "com.fasterxml.jackson.core", "medium", 5.3, "2.18", "2.0.0", true, "2.18.8", false, "2.18.8", true, "INET_SOCKET_ADDRESS", "仅当把不可信 JSON 绑定到含 InetSocketAddress 字段的类型上(绑定时就会发起 DNS 查询)", "InetSocketAddress", "InetSocketAddress deserialization triggers eager DNS resolution (SSRF) in jackson-databind", "JDKFromStringDeserializer constructed InetSocketAddress with new InetSocketAddress(host, port), which performs eager DNS name resolution for hostname inputs at deserialization time. An application th…");
        add("GHSA-hgj6-7826-r7m5", "CVE-2026-54514", "com.fasterxml.jackson.core", "medium", 5.3, "2.21", "2.19.0", true, "2.21.4", false, "2.21.4", true, "INET_SOCKET_ADDRESS", "仅当把不可信 JSON 绑定到含 InetSocketAddress 字段的类型上(绑定时就会发起 DNS 查询)", "InetSocketAddress", "InetSocketAddress deserialization triggers eager DNS resolution (SSRF) in jackson-databind", "JDKFromStringDeserializer constructed InetSocketAddress with new InetSocketAddress(host, port), which performs eager DNS name resolution for hostname inputs at deserialization time. An application th…");
        add("GHSA-hgj6-7826-r7m5", "CVE-2026-54514", "com.fasterxml.jackson.core", "medium", 5.3, "3.1", "3.0.0", true, "3.1.4", false, "3.1.4", false, "INET_SOCKET_ADDRESS", "仅当把不可信 JSON 绑定到含 InetSocketAddress 字段的类型上(绑定时就会发起 DNS 查询)", "InetSocketAddress", "InetSocketAddress deserialization triggers eager DNS resolution (SSRF) in jackson-databind", "JDKFromStringDeserializer constructed InetSocketAddress with new InetSocketAddress(host, port), which performs eager DNS name resolution for hostname inputs at deserialization time. An application th…");
        add("GHSA-hgj6-7826-r7m5", "CVE-2026-54514", "tools.jackson.core", "medium", 5.3, "2.21", "2.19.0", true, "2.21.4", false, "2.21.4", false, "INET_SOCKET_ADDRESS", "仅当把不可信 JSON 绑定到含 InetSocketAddress 字段的类型上(绑定时就会发起 DNS 查询)", "InetSocketAddress", "InetSocketAddress deserialization triggers eager DNS resolution (SSRF) in jackson-databind", "JDKFromStringDeserializer constructed InetSocketAddress with new InetSocketAddress(host, port), which performs eager DNS name resolution for hostname inputs at deserialization time. An application th…");
        add("GHSA-hgj6-7826-r7m5", "CVE-2026-54514", "tools.jackson.core", "medium", 5.3, "3.1", "3.0.0", true, "3.1.4", false, "3.1.4", true, "INET_SOCKET_ADDRESS", "仅当把不可信 JSON 绑定到含 InetSocketAddress 字段的类型上(绑定时就会发起 DNS 查询)", "InetSocketAddress", "InetSocketAddress deserialization triggers eager DNS resolution (SSRF) in jackson-databind", "JDKFromStringDeserializer constructed InetSocketAddress with new InetSocketAddress(host, port), which performs eager DNS name resolution for hostname inputs at deserialization time. An application th…");
        add("GHSA-5jmj-h7xm-6q6v", "CVE-2026-54515", "com.fasterxml.jackson.core", "medium", 5.3, "3.1", "3.1.0", true, "3.1.4", false, "3.1.4", false, "CASE_INSENSITIVE", "仅当同时开启了大小写不敏感匹配(@JsonFormat 的 ACCEPT_CASE_INSENSITIVE_PROPERTIES)并依赖逐属性的 @JsonIgnoreProperties 把字段挡在外面", "ACCEPT_CASE_INSENSITIVE_PROPERTIES,@JsonIgnoreProperties", "Case-insensitive deserialization bypasses per-property @JsonIgnoreProperties in jackson-databind", "In BeanDeserializerBase.createContextual(), per-property @JsonIgnoreProperties exclusions are applied by _handleByNameInclusion(), producing a contextual deserializer whose BeanPropertyMap has the ig…");
        add("GHSA-5jmj-h7xm-6q6v", "CVE-2026-54515", "tools.jackson.core", "medium", 5.3, "3.1", "3.1.0", true, "3.1.4", false, "3.1.4", true, "CASE_INSENSITIVE", "仅当同时开启了大小写不敏感匹配(@JsonFormat 的 ACCEPT_CASE_INSENSITIVE_PROPERTIES)并依赖逐属性的 @JsonIgnoreProperties 把字段挡在外面", "ACCEPT_CASE_INSENSITIVE_PROPERTIES,@JsonIgnoreProperties", "Case-insensitive deserialization bypasses per-property @JsonIgnoreProperties in jackson-databind", "In BeanDeserializerBase.createContextual(), per-property @JsonIgnoreProperties exclusions are applied by _handleByNameInclusion(), producing a contextual deserializer whose BeanPropertyMap has the ig…");
        add("GHSA-5jmj-h7xm-6q6v", "CVE-2026-54515", "com.fasterxml.jackson.core", "medium", 5.3, "2.18", "2.8.0", true, "2.18.9", false, "2.18.9", true, "CASE_INSENSITIVE", "仅当同时开启了大小写不敏感匹配(@JsonFormat 的 ACCEPT_CASE_INSENSITIVE_PROPERTIES)并依赖逐属性的 @JsonIgnoreProperties 把字段挡在外面", "ACCEPT_CASE_INSENSITIVE_PROPERTIES,@JsonIgnoreProperties", "Case-insensitive deserialization bypasses per-property @JsonIgnoreProperties in jackson-databind", "In BeanDeserializerBase.createContextual(), per-property @JsonIgnoreProperties exclusions are applied by _handleByNameInclusion(), producing a contextual deserializer whose BeanPropertyMap has the ig…");
        add("GHSA-5jmj-h7xm-6q6v", "CVE-2026-54515", "com.fasterxml.jackson.core", "medium", 5.3, "2.21", "2.19.0", true, "2.21.5", false, "2.21.5", true, "CASE_INSENSITIVE", "仅当同时开启了大小写不敏感匹配(@JsonFormat 的 ACCEPT_CASE_INSENSITIVE_PROPERTIES)并依赖逐属性的 @JsonIgnoreProperties 把字段挡在外面", "ACCEPT_CASE_INSENSITIVE_PROPERTIES,@JsonIgnoreProperties", "Case-insensitive deserialization bypasses per-property @JsonIgnoreProperties in jackson-databind", "In BeanDeserializerBase.createContextual(), per-property @JsonIgnoreProperties exclusions are applied by _handleByNameInclusion(), producing a contextual deserializer whose BeanPropertyMap has the ig…");
        add("GHSA-5jmj-h7xm-6q6v", "CVE-2026-54515", "com.fasterxml.jackson.core", "medium", 5.3, "2.22", "2.22.0", true, "2.22.1", false, "2.22.1", true, "CASE_INSENSITIVE", "仅当同时开启了大小写不敏感匹配(@JsonFormat 的 ACCEPT_CASE_INSENSITIVE_PROPERTIES)并依赖逐属性的 @JsonIgnoreProperties 把字段挡在外面", "ACCEPT_CASE_INSENSITIVE_PROPERTIES,@JsonIgnoreProperties", "Case-insensitive deserialization bypasses per-property @JsonIgnoreProperties in jackson-databind", "In BeanDeserializerBase.createContextual(), per-property @JsonIgnoreProperties exclusions are applied by _handleByNameInclusion(), producing a contextual deserializer whose BeanPropertyMap has the ig…");
        add("GHSA-9fxm-vc8v-hj55", "CVE-2026-54516", "com.fasterxml.jackson.core", "medium", 5.3, "2.21", "2.21.0", true, "2.21.4", false, "2.21.4", true, "IGNORED_SETTER_RENAME", "仅当同一个属性上 getter 带 @JsonProperty 改了名、setter 带 @JsonIgnore(即「只读不写」的写法)", "@JsonIgnore,@JsonProperty", "Renamed @JsonIgnore'd setters can deserialize via private fields in jackson-databind", "POJOPropertiesCollector._renameProperties() allows a property with @JsonProperty(\"renamed\") on the getter and @JsonIgnore on the setter to be renamed rather than dropped. With MapperFeature.INFER_PRO…");
        add("GHSA-9fxm-vc8v-hj55", "CVE-2026-54516", "com.fasterxml.jackson.core", "medium", 5.3, "3.1", "3.0.0", true, "3.1.4", false, "3.1.4", false, "IGNORED_SETTER_RENAME", "仅当同一个属性上 getter 带 @JsonProperty 改了名、setter 带 @JsonIgnore(即「只读不写」的写法)", "@JsonIgnore,@JsonProperty", "Renamed @JsonIgnore'd setters can deserialize via private fields in jackson-databind", "POJOPropertiesCollector._renameProperties() allows a property with @JsonProperty(\"renamed\") on the getter and @JsonIgnore on the setter to be renamed rather than dropped. With MapperFeature.INFER_PRO…");
        add("GHSA-9fxm-vc8v-hj55", "CVE-2026-54516", "tools.jackson.core", "medium", 5.3, "3.1", "3.0.0", true, "3.1.4", false, "3.1.4", true, "IGNORED_SETTER_RENAME", "仅当同一个属性上 getter 带 @JsonProperty 改了名、setter 带 @JsonIgnore(即「只读不写」的写法)", "@JsonIgnore,@JsonProperty", "Renamed @JsonIgnore'd setters can deserialize via private fields in jackson-databind", "POJOPropertiesCollector._renameProperties() allows a property with @JsonProperty(\"renamed\") on the getter and @JsonIgnore on the setter to be renamed rather than dropped. With MapperFeature.INFER_PRO…");
        add("GHSA-5hh8-q8hv-fr38", "CVE-2026-54517", "com.fasterxml.jackson.core", "medium", 5.3, "2.21", "2.21.0", true, "2.21.4", false, "2.21.4", true, "JSONVIEW", "仅当用 @JsonView 做写入侧权限门控,且被门控的是 setterless 的 Collection/Map 属性", "@JsonView", "@JsonView bypass for setterless creator properties in jackson-databind", "In BeanDeserializer._deserializeUsingPropertyBased, the active-view (@JsonView) filter was applied only to creator properties; the regular property-buffering branch performed no prop.visibleInView(ac…");
        add("GHSA-5hh8-q8hv-fr38", "CVE-2026-54517", "com.fasterxml.jackson.core", "medium", 5.3, "3.1", "3.0.0", true, "3.1.4", false, "3.1.4", false, "JSONVIEW", "仅当用 @JsonView 做写入侧权限门控,且被门控的是 setterless 的 Collection/Map 属性", "@JsonView", "@JsonView bypass for setterless creator properties in jackson-databind", "In BeanDeserializer._deserializeUsingPropertyBased, the active-view (@JsonView) filter was applied only to creator properties; the regular property-buffering branch performed no prop.visibleInView(ac…");
        add("GHSA-5hh8-q8hv-fr38", "CVE-2026-54517", "tools.jackson.core", "medium", 5.3, "3.1", "3.0.0", true, "3.1.4", false, "3.1.4", true, "JSONVIEW", "仅当用 @JsonView 做写入侧权限门控,且被门控的是 setterless 的 Collection/Map 属性", "@JsonView", "@JsonView bypass for setterless creator properties in jackson-databind", "In BeanDeserializer._deserializeUsingPropertyBased, the active-view (@JsonView) filter was applied only to creator properties; the regular property-buffering branch performed no prop.visibleInView(ac…");
        add("GHSA-rcqc-6cw3-h962", "CVE-2026-54518", "com.fasterxml.jackson.core", "medium", 6.5, "2.21", "2.21.0", true, "2.21.4", false, "2.21.4", true, "JSONVIEW_UNWRAPPED", "仅当 @JsonView 与 @JsonUnwrapped 同时标在构造器(creator)参数上", "@JsonView,@JsonUnwrapped", "@JsonView bypass for unwrapped creator parameters in jackson-databind", "UnwrappedPropertyHandler.processUnwrappedCreatorProperties() replays buffered JSON into creator parameters but never consults prop.visibleInView(activeView). The normal property-based creator path ga…");
        add("GHSA-rcqc-6cw3-h962", "CVE-2026-54518", "tools.jackson.core", "medium", 6.5, "3.1", "3.0.0", true, "3.1.4", false, "3.1.4", true, "JSONVIEW_UNWRAPPED", "仅当 @JsonView 与 @JsonUnwrapped 同时标在构造器(creator)参数上", "@JsonView,@JsonUnwrapped", "@JsonView bypass for unwrapped creator parameters in jackson-databind", "UnwrappedPropertyHandler.processUnwrappedCreatorProperties() replays buffered JSON into creator parameters but never consults prop.visibleInView(activeView). The normal property-based creator path ga…");
        add("GHSA-3pjw-73gf-8qr5", "CVE-2026-59888", "com.fasterxml.jackson.core", "medium", 6.5, "2.18", "2.15.0", true, "2.18.8", false, "2.18.8", true, "RECORD_NAMING", "仅当用 Java Record + PropertyNamingStrategy(命名策略),且靠 @JsonIgnore 挡住某个组件", "record,PropertyNamingStrategy,@JsonIgnore", "`@JsonIgnore` on a Record property is bypassed with a PropertyNamingStrategy in jackson-databind…", "For Java Records, POJOPropertiesCollector._removeUnwantedIgnorals() records a @JsonIgnore-annotated component under its original implicit name before _renameUsing() applies the PropertyNamingStrategy…");
        add("GHSA-3pjw-73gf-8qr5", "CVE-2026-59888", "com.fasterxml.jackson.core", "medium", 6.5, "2.21", "2.19.0", true, "2.21.4", false, "2.21.4", true, "RECORD_NAMING", "仅当用 Java Record + PropertyNamingStrategy(命名策略),且靠 @JsonIgnore 挡住某个组件", "record,PropertyNamingStrategy,@JsonIgnore", "`@JsonIgnore` on a Record property is bypassed with a PropertyNamingStrategy in jackson-databind…", "For Java Records, POJOPropertiesCollector._removeUnwantedIgnorals() records a @JsonIgnore-annotated component under its original implicit name before _renameUsing() applies the PropertyNamingStrategy…");
        add("GHSA-3pjw-73gf-8qr5", "CVE-2026-59888", "tools.jackson.core", "medium", 6.5, "3.1", "3.0.0", true, "3.1.4", false, "3.1.4", true, "RECORD_NAMING", "仅当用 Java Record + PropertyNamingStrategy(命名策略),且靠 @JsonIgnore 挡住某个组件", "record,PropertyNamingStrategy,@JsonIgnore", "`@JsonIgnore` on a Record property is bypassed with a PropertyNamingStrategy in jackson-databind…", "For Java Records, POJOPropertiesCollector._removeUnwantedIgnorals() records a @JsonIgnore-annotated component under its original implicit name before _renameUsing() applies the PropertyNamingStrategy…");
        add("GHSA-5gvw-p9qm-jgwh", "CVE-2026-59889", "com.fasterxml.jackson.core", "medium", 6.5, "2.21", "2.21.0", true, "2.21.5", false, "2.21.5", true, "JSONVIEW_UNWRAPPED", "仅当同一个属性上同时有 @JsonView 和 @JsonUnwrapped(容器属性,非构造器参数)", "@JsonView,@JsonUnwrapped", "@JsonView bypassed for @JsonUnwrapped container properties on deserialization: a…", "UnwrappedPropertyHandler.processUnwrapped() replays the buffered JSON for a @JsonUnwrapped property by iterating its properties and calling prop.deserializeAndSet() with no prop.visibleInView(ctxt.ge…");
        add("GHSA-5gvw-p9qm-jgwh", "CVE-2026-59889", "tools.jackson.core", "medium", 6.5, "3.1", "3.0.0", true, "3.1.4", true, "3.1.5", true, "JSONVIEW_UNWRAPPED", "仅当同一个属性上同时有 @JsonView 和 @JsonUnwrapped(容器属性,非构造器参数)", "@JsonView,@JsonUnwrapped", "@JsonView bypassed for @JsonUnwrapped container properties on deserialization: a…", "UnwrappedPropertyHandler.processUnwrapped() replays the buffered JSON for a @JsonUnwrapped property by iterating its properties and calling prop.deserializeAndSet() with no prop.visibleInView(ctxt.ge…");
        add("GHSA-5gvw-p9qm-jgwh", "CVE-2026-59889", "com.fasterxml.jackson.core", "medium", 6.5, "2.18", "2.18.0", true, "2.18.8", true, "2.18.9", true, "JSONVIEW_UNWRAPPED", "仅当同一个属性上同时有 @JsonView 和 @JsonUnwrapped(容器属性,非构造器参数)", "@JsonView,@JsonUnwrapped", "@JsonView bypassed for @JsonUnwrapped container properties on deserialization: a…", "UnwrappedPropertyHandler.processUnwrapped() replays the buffered JSON for a @JsonUnwrapped property by iterating its properties and calling prop.deserializeAndSet() with no prop.visibleInView(ctxt.ge…");
        add("GHSA-5gvw-p9qm-jgwh", "CVE-2026-59889", "com.fasterxml.jackson.core", "medium", 6.5, "2.22", "2.22.0", true, "2.22.1", false, "2.22.1", true, "JSONVIEW_UNWRAPPED", "仅当同一个属性上同时有 @JsonView 和 @JsonUnwrapped(容器属性,非构造器参数)", "@JsonView,@JsonUnwrapped", "@JsonView bypassed for @JsonUnwrapped container properties on deserialization: a…", "UnwrappedPropertyHandler.processUnwrapped() replays the buffered JSON for a @JsonUnwrapped property by iterating its properties and calling prop.deserializeAndSet() with no prop.visibleInView(ctxt.ge…");
        add("GHSA-5gvw-p9qm-jgwh", "CVE-2026-59889", "tools.jackson.core", "medium", 6.5, "3.2", "3.2.0", true, "3.2.1", false, "3.2.1", true, "JSONVIEW_UNWRAPPED", "仅当同一个属性上同时有 @JsonView 和 @JsonUnwrapped(容器属性,非构造器参数)", "@JsonView,@JsonUnwrapped", "@JsonView bypassed for @JsonUnwrapped container properties on deserialization: a…", "UnwrappedPropertyHandler.processUnwrapped() replays the buffered JSON for a @JsonUnwrapped property by iterating its properties and calling prop.deserializeAndSet() with no prop.visibleInView(ctxt.ge…");
        add("GHSA-mhm7-754m-9p8w", "", "com.fasterxml.jackson.core", "medium", 6.5, "2.18", "2.18.0", true, "2.18.8", true, "2.18.9", true, "JSONVIEW_EXTERNAL_TYPEID", "仅当构造器参数上同时有 @JsonView 和 @JsonTypeInfo(include = As.EXTERNAL_PROPERTY)", "@JsonView,@JsonTypeInfo,EXTERNAL_PROPERTY", "`@JsonView` bypass for creator properties with `@JsonTypeInfo(include=As.EXTERNAL_PROPERTY)`", "In BeanDeserializer.deserializeUsingPropertyBasedWithExternalTypeId, the active-view (@JsonView) filter was applied only to the regular bean-property branch; the creator-property branch performed no …");
        add("GHSA-mhm7-754m-9p8w", "", "com.fasterxml.jackson.core", "medium", 6.5, "2.21", "2.21.0", true, "2.21.4", true, "2.21.5", true, "JSONVIEW_EXTERNAL_TYPEID", "仅当构造器参数上同时有 @JsonView 和 @JsonTypeInfo(include = As.EXTERNAL_PROPERTY)", "@JsonView,@JsonTypeInfo,EXTERNAL_PROPERTY", "`@JsonView` bypass for creator properties with `@JsonTypeInfo(include=As.EXTERNAL_PROPERTY)`", "In BeanDeserializer.deserializeUsingPropertyBasedWithExternalTypeId, the active-view (@JsonView) filter was applied only to the regular bean-property branch; the creator-property branch performed no …");
    }

    private static void add(String ghsaId, String cveId, String groupId, String severity,
                            double cvss, String branch,
                            String low, boolean lowIncl, String high, boolean highIncl,
                            String fixedIn, boolean fixedAvailable,
                            String condKind, String condText, String markers,
                            String title, String desc) {
        ALL.add(new Cve(ghsaId, cveId, groupId, severity, cvss, branch,
                        low, lowIncl, high, highIncl, fixedIn, fixedAvailable,
                        condKind, condText,
                        markers.isEmpty() ? List.of() : List.of(markers.split(",")),
                        title, desc));
    }

    public static List<Cve> all() { return Collections.unmodifiableList(ALL); }
}
